code4romania/rezultate-vot-client

- .gitignore
- src/components/AppLayout.tsx
- src/components/BallotTabs.module.scss
- src/components/toast/context.jsx
- src/components/toast/withToastProvider.jsx
> Lazy load for pages

- src/components/BallotPage.tsx
- src/components/NewsSection.module.scss
- src/components/NewsSection.tsx
> news feed margin, selector help text

- src/components/AppLayout.tsx
- src/components/CookiePolicyPage.tsx
- src/components/Footer.tsx
> cookie policy

- src/components/BallotPage.module.scss
- src/components/BallotPage.tsx
> show update interval info text

- package.json
- yarn.lock
Closes #58 
🚨 **DO NOT MERGE UNTIL THEW NEW VERSION OF COMPONENTS IS BUILT AND PUBLISHED** 🚨
> Update reusable components to include the new not-found message

- package.json
- public/site.webmanifest
- src/components/ResultsTab.tsx
- yarn.lock
> Change header in ResultTable

- src/components/BallotTabs.tsx
Close #69 
**[IMPORTANT] This label has to be active starting 21.00 (it is just for results)**
> Show extra tab "primaria generala"

- src/components/BallotPage.tsx
- src/components/Header.tsx
Revert live news feed header link changes
> Revert news feed link

- src/components/AboutPage.module.scss
- src/components/BallotPage.tsx
- src/components/BallotTabs.tsx
Active state-ul pe tab se comporta un pic diferit. Tab-ul apare activ si pe Rezultate Vot si pe Primarul capitalei, pentru ca path-ul este acelasi, difera doar query string-ul.
> Add Primarul capitalei tab. Fix responsive design on about page

- package.json
- yarn.lock
Update version of reusable-components.
> Update reusable-components version

- .github/workflows/deploy.yml
Update GHA for staging environment.
> Update GHA for staging

- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-staging.yml
- .github/workflows/deploy.yml
- package.json
- src/components/BallotPage.tsx
- src/components/NewsCardWidget.tsx
- src/components/ResultsTab.tsx
- yarn.lock
Merge develop branch to master.
> Merge develop to master

- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-staging.yml
> Update environment variables

- package.json
- yarn.lock
Update version of reusable components.
> Update reusable components version

- package.json
- src/components/ResultsTab.tsx
- yarn.lock
Should fix this: https://github.com/code4romania/rezultate-vot-client/issues/86
Might be that more work needs to be done to make sure all cases are covered
> All elections to use the summary section with the stackbar, table and map

- src/components/ResultsTab.tsx
> Fixing previous PR 

- src/components/AppLayout.tsx
- src/components/EmbedButton.tsx
- src/components/EmbedWrapper.module.scss
- src/components/NewsCardPage.module.scss
- src/components/NewsCardPage.tsx
- src/components/NewsCardWidget.module.scss
- src/components/NewsCardWidget.tsx
- src/components/NewsEmbedButton.module.scss
- src/components/NewsEmbedButton.tsx
- src/components/NewsSection.tsx
- src/components/NewsWidget.tsx
> Add news item embed route and buttons

- package.json
- yarn.lock
Update latest version of reusable components.
> Update RC version

- package.json
- src/components/BallotPage.tsx
- src/components/CandidatesTab.tsx
- yarn.lock
> Candidates tab enhancements

- README.md
Update README.md with live and staging links
> Update README.md with live and staging links

- src/components/CandidatesTab.tsx
> Fix candidates tab on locality view

- src/components/CandidatesTab.tsx
> Fix typo and locality view when countyId is missing

- src/components/BallotPage.tsx
> Fix compatibility scope for candidates tab

- package.json
- yarn.lock
> Partial results

- src/components/BallotPage.module.scss
- src/components/BallotPage.tsx
- src/components/Banner.module.scss
- src/components/Banner.tsx
> Add margin-bottom to banner on ballot page

- README.md
- package.json
- src/components/AboutPage.tsx
- src/components/BallotPage.module.scss
- src/components/BallotPage.tsx
- src/components/Banner.module.scss
- src/components/Banner.tsx
- src/components/CandidatesTab.tsx
- yarn.lock
Merge develop to master branch.
> Merge develop to master branch

- package.json
- yarn.lock
> Add diaspora fix

- package.json
- yarn.lock
> Various fixes

- src/components/BallotPage.tsx
- src/components/EmbedWrapper.tsx
- src/components/Logo.module.scss
- src/components/Logo.tsx
Redirects by default to results page
> redirect to results page

- src/components/EmbedWrapper.module.scss
- src/components/EmbedWrapper.tsx
> Change embed branding strip

- src/components/Banner.tsx
> Change main banner text

- public/favicon.svg
- public/index.html
- public/site.webmanifest
Imported the new favicon provided.
> Change favicon

- src/components/Header.custom.scss
- src/components/Header.tsx
HereMap changes to hide the logo and adjust the copyright font/placement
> HereMap adjustments

- package.json
- src/components/ResultsTab.module.scss
- src/components/TurnoutTab.tsx
- yarn.lock
Added the logic to show candidates in the Turnout section depending on the type of election/candidate
> Show Candidates in Turnout Page
